"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentRegistry__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DocumentRegistry__factory_1 = require("./DocumentRegistry__factory");
Object.defineProperty(exports, "DocumentRegistry__factory", { enumerable: true, get: function () { return DocumentRegistry__factory_1.DocumentRegistry__factory; } });
//# sourceMappingURL=index.js.map